version: '3'
services:
  app:
    container_name: nest-wrike-slack
    image: nest-wrike-slack
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run start:dev
    volumes:
      - .:/app
      - /app/node_modules
